[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.22"

[features]
resolution = false
skip-lint = false

[programs.localnet]
solana_pastel_bridge = "G7uVj97ovf94Eayow7Cujyt2eqJirDoiU65xbaE323fV"
solana_pastel_oracle = "HV8WdfKMxxrEom7bTNzCqU7iCEA3ueKmntJzbFPVG61E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
